steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecotrack-db', '-f', 'Dockerfile.db', '.']
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecotrack-db']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecotrack-db'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecotrack-db'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5432'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'POSTGRES_DB=ecotrack,POSTGRES_USER=ecotrack_user'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD=ecotrack-db-password:latest'

images:
  - 'gcr.io/$PROJECT_ID/ecotrack-db' 