import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1737240444787 implements MigrationInterface {
    name = 'Migrations1737240444787'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "journeys" DROP CONSTRAINT "FK_journeys_user"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP CONSTRAINT "FK_journeys_vehicle"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP CONSTRAINT "journeys_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP CONSTRAINT "journeys_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "fk_messages_recipient"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "fk_messages_sender"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "fk_message_attachments_message"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journeys_co2_emissions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journeys_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journeys_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_recipient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_sender"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "chk_title_length"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "chk_content_length"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "chk_file_size"`);
        await queryRunner.query(`CREATE TABLE "user_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "timestamp" TIMESTAMP NOT NULL, "accuracy" numeric(5,2), "speed" numeric(5,2), "heading" numeric(5,2), "is_active" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4afd5dae13173e88183db3cd210" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_437edca703095b237b5bdb35e2" ON "user_locations" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "carbon_goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target_co2" numeric(10,2) NOT NULL, "previous_month_co2" numeric(10,2) NOT NULL, "target_month" date NOT NULL, "user_id" uuid, "is_global" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f03b16cb0dd147d7c19cf4a6da7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "distance"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "co2_emission"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "route_data"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "vehicle_type"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "failed_login_attempts" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_latitude" double precision`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_longitude" double precision`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_location_update" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD "checksum" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD "is_safe" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "journeys" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "transport_mode"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "transport_mode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "start_location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "end_location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "start_time" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "end_time" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journeys" ALTER COLUMN "distance_km" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" ALTER COLUMN "co2_emissions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "brand" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "model" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "CHK_d2cbabe6bdea23ae30c6cdb5ad" CHECK (length(content) <= 2000)`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "CHK_2a2889cd74c1bdbd7c7e69522c" CHECK (length(title) <= 100)`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "CHK_f4e40ed5b99b9c258187e0a618" CHECK (file_size <= 5242880)`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD CONSTRAINT "FK_6479cea41ce0ce155e8bbb7c85c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD CONSTRAINT "FK_cbdda1979cbb4990d13c765e90c" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_88b36924d769e4df751bcfbf249" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_locations" ADD CONSTRAINT "FK_437edca703095b237b5bdb35e22" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_566c3d68184e83d4307b86f85ab" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "FK_bf65c3db8657cef6197b68b8c88" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carbon_goals" ADD CONSTRAINT "FK_6bf3532579dff211ff54d6c898d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "carbon_goals" DROP CONSTRAINT "FK_6bf3532579dff211ff54d6c898d"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "FK_bf65c3db8657cef6197b68b8c88"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_566c3d68184e83d4307b86f85ab"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "user_locations" DROP CONSTRAINT "FK_437edca703095b237b5bdb35e22"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_88b36924d769e4df751bcfbf249"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP CONSTRAINT "FK_cbdda1979cbb4990d13c765e90c"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP CONSTRAINT "FK_6479cea41ce0ce155e8bbb7c85c"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "CHK_f4e40ed5b99b9c258187e0a618"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "CHK_2a2889cd74c1bdbd7c7e69522c"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "CHK_d2cbabe6bdea23ae30c6cdb5ad"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "model" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "brand" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journeys" ALTER COLUMN "co2_emissions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" ALTER COLUMN "distance_km" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "end_time"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "end_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "start_time"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "start_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "end_location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "start_location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "transport_mode"`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "transport_mode" character varying(50) NOT NULL DEFAULT 'car'`);
        await queryRunner.query(`ALTER TABLE "journeys" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP COLUMN "is_safe"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP COLUMN "checksum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_location_update"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_longitude"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_latitude"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "failed_login_attempts"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "vehicle_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "status" character varying(50) DEFAULT 'planned'`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "route_data" jsonb`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "co2_emission" double precision`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD "distance" double precision`);
        await queryRunner.query(`DROP TABLE "carbon_goals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_437edca703095b237b5bdb35e2"`);
        await queryRunner.query(`DROP TABLE "user_locations"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "chk_file_size" CHECK ((file_size <= 5242880))`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "chk_content_length" CHECK ((length(content) <= 2000))`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "chk_title_length" CHECK ((length((title)::text) <= 100))`);
        await queryRunner.query(`CREATE INDEX "idx_messages_sender" ON "messages" ("sender_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_recipient" ON "messages" ("is_read", "recipient_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_journeys_vehicle_id" ON "journeys" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journeys_user_id" ON "journeys" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journeys_co2_emissions" ON "journeys" ("co2_emissions") `);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "fk_message_attachments_message" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "fk_messages_sender" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "fk_messages_recipient" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD CONSTRAINT "journeys_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD CONSTRAINT "journeys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD CONSTRAINT "FK_journeys_vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD CONSTRAINT "FK_journeys_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
